# Generated by Django 5.0.2 on 2024-02-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(default='test', max_length=99),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
